config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :after_signup
  root to: 'pages#home'
  resource :dashboard, only: :show
  get "/results", to: 'users#index', as: "results"
  get "/autocomplete", to: 'users#autocomplete'
  get "/allbookings", to: 'dashboards#allbookings', as: "allbookings"
  get "/allearnings", to: 'dashboards#allearnings', as: "allearnings"
  get "/users/:id", to: 'users#profile', as: "profile"

  resources :chats, only: [:index, :create, :show] do
   resources :messages, only:  :create
  end
  resources :users do
  	resources :bookings, only: :create
    resources :reviews, only: [:create]
  end

  resources :bookings, only: :update do
     resources :payments, only: :new
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  monetize :price_cents
  has_many :learning_subjects
  has_many :teaching_subjects
  has_many :received_bookings, foreign_key: :mentor_id, class_name: 'Booking'
  has_many :sent_bookings, foreign_key: :student_id, class_name: 'Booking'
  has_many :received_reviews, foreign_key: :reviewed_id, class_name: "Review", dependent: :destroy
  has_many :sent_reviews, foreign_key: :reviewer_id, class_name: "Review", dependent: :destroy
  accepts_nested_attributes_for :learning_subjects
  accepts_nested_attributes_for :teaching_subjects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo

  validates :email, :name, :surname, presence: true
  validates :bio, presence: true, on: :update, length: { minimum: 40 }
  validates :language, :location, presence: true, on: :update

  def full_name
    self.name.capitalize + ' ' + self.surname.capitalize
  end

  def self.languages_from_search(users)
    users.map(&:language).uniq
  end

  def average_ratings
    return if received_reviews.count.nil?

    total_stars = received_reviews.pluck(:stars).sum
    total_stars.fdiv(received_reviews.count).round(1)
  end

  def profile_completetion_percentage
    
  end

  def completion_percentage
    total_points = 2
    total_points += 1 if location.present?
    total_points += 1 if bio.present?
    total_points += 1 if photo.attached?
    total_points * 2 * 10
  end

  def earnings
     received_bookings.sum(:total_cents)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    query = params[:query]
    @users = policy_scope(User).paginate(page: params[:page], per_page: 5)
    if params[:type] == 'student'
      @users = @users.joins(:learning_subjects).where.not(learning_subjects: { id: nil }).distinct
    else
      @users = @users.joins(:teaching_subjects).where.not(teaching_subjects: { id: nil }).distinct
    end
    if query.present?
      if params[:type] == 'student'
        @users = @users.joins(learning_subjects: :subject).where("subjects.name ILIKE ?", query)
      else
        @users = @users.joins(teaching_subjects: :subject).where("subjects.name ILIKE ?", query)
      end
    end

    if params[:city].present?
      @users = @users.where("location = ?", params[:city])
    end

    if params[:language].present?
      @users = @users.where("language = ?", params[:language])
    end

    if params[:price].present?
      if params[:price] == 'low_first'
      @users = @users.order(price_cents: :asc)
    else
      @users = @users.order(price_cents: :desc)
    end
    end
  end

  def autocomplete

    if params[:query].present?
      subjects = Subject.where("name ILIKE ?", "#{params[:query]}%").limit(4)
    else
      subjects = []
    end
    skip_authorization
    render json: { subjects: subjects.pluck(:name) }
  end

  def profile
    @user = User.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    @reviews = Review.where(reviewed_id: @user.id)
    authorize @user
  end
end

app/views/users/index.html.erb
<% content_for :title, " Find the perfect buddies| Study Buddy" %>
<% content_for :description, "Over #{@users.count} students/mentors use study buddy, join us to study better, study fast" %>
<div class="banner" style="margin-bottom: 150px;background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "results_banner.png" %>);">
  <div class="container" data-controller="autocomplete">
    <div class="row">
      <div class="col-sm-12 col-lg-5">
        <div class="filter-box">
          <form action="/results">
            <h5 class="sub-heading ">What do you want to study?</h5>
            <input placeholder="Search for a subject" autocomplete="off" data-target='autocomplete.input' data-action="keyup->autocomplete#suggest" type="text" name="query" id="search" value="<%= params[:query] %>">
              <ul data-target='autocomplete.suggestions' id="display-sugg" class="">
              </ul>
          </form>
          <div class="type my-4">
            <h5 class="sub-heading">Who do you want to study with?</h5>
              <%= link_to 'Students', results_path(type: 'student', query: params[:query]), class: "btn btn-ghost #{'active-btn' if params[:type]}" %>
              <%= link_to 'Mentors', results_path( query: params[:query]), class: "btn btn-ghost #{'active-btn' if !params[:type]}"  %>
          </div>

            <h5 class="sub-heading">You can also filter by:</h5>
            <div class="extra-filter d-flex">
              <div class="dropdown">
              <a class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Languages
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'All languages', results_path(request.params.merge(language: '')), class: 'dropdown-item'   %>
                <% User.languages_from_search(@users).each do |language| %>
                  <%= link_to language, results_path(request.params.merge(language: language)), class: 'dropdown-item'   %>
                <% end %>
              </div>
            </div>
            <% if !params[:type] %>
              <div class="dropdown mx-3">
                <a class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Price
                </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'Lowest first', results_path(request.params.merge(price: 'low_first')), class: 'dropdown-item'   %>
                <%= link_to 'Highest first', results_path(request.params.merge(price: 'highest_first')), class: 'dropdown-item'   %>
              </div>
            </div>
          <% end %>
            <% if user_signed_in? %>
              <i class="fas fa-compass ml-3 m-1"></i>
              <% if params[:city].present? %>
                <%= link_to 'Anywhere', results_path(request.params.merge(city: '')), style: 'color: black'  %>
                <% else %>
              <%= link_to 'In my city', results_path(request.params.merge(city: current_user.location)), style: 'color: black'  %>
              <% end %>
           <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row my-4">
    <% if   @users.count == 0 %>
      <h4 class="col-12 text-center">
         Looks like we couldn't find any <%= params[:type] ? 'Student' : 'Mentor' %><%= " for #{params[:query]} " if params[:query].present? && params[:query] != '' %>
         <%= "in #{params[:city]} " if present? %> </h4>
      <div class="col-12 text-center my-5">
        <img src="https://image.flaticon.com/icons/svg/2353/2353678.svg" width="200" alt="">
      </div>
    <% else %>
      <% @users.each do |u| %>
        <div class="col-12 my-2 mx-auto">
          <div class="card-user">
            <div class="row">
              <div class="col-sm-12 col-lg-2 mx-auto text-center">
                <div class="card-left text-center mx-auto">
                <% if u.photo.attached? %>
                  <%= cl_image_tag u.photo.key, crop: :thumb, gravity: :face, width: 120, height: 120, class: "rounded-circle dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
                <% else %>
                 <img src="https://image.flaticon.com/icons/svg/847/847969.svg" width="120" class="rounded-circle dropdown-toggle", id="navbarDropdown", data-toggle="dropdown", aria-haspopup="true", aria-expanded="false"  >
                <% end %>
                <% unless u.last_seen_at.nil? || u.last_seen_at < 5.minutes.ago %>
                  <div class="badge badge-success">Online</div>
                <% end %>
                <%= link_to 'Get help', profile_path(u), class: 'btn btn-flat mt-4' %>
              </div>
              </div>

              <div class="col-sm-12 col-lg-10">
                <h3> <strong><%= u.full_name  %></strong> </h3>
                <% u.teaching_subjects.each do |s| %>
                  <div class="tag"><%= s.name %></div>
                <% end %>
                <div class="extra-info">
                  <i class="far fa-star"></i>
                  <%= u.average_ratings if u.received_reviews.present? %>
                  (<%= pluralize( u.received_reviews.count, 'review' ) %>)
                  <i class="fas fa-language"></i>
                  <%= u.language %>
                  <i class="fas fa-map-marker-alt"></i>
                  <%= u.location %>
                  <% if !params[:type] %>
                  <i class="fas fa-euro-sign"></i>
                  <%= humanized_money(u.price)%>/hour
                  <% end %>
                </div>

                <p><%= u.bio %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="col-12">
    <%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<% content_for :title, "#{@user.full_name}'s profile | Study Buddy" %>
<% content_for :description, "#{@user.bio}" %>
<div style="height: 100px;">

    </div>
<div class="container my-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12 text-center">
      <div class="profile-box">
        <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, crop: :thumb, gravity: :face, width: 120, height: 120, class: "rounded-circle dropdown-toggle", id: "navbarDropdown"  %>
        <% else %>
          <img src="https://image.flaticon.com/icons/svg/847/847969.svg" width="120" alt="">
        <% end %>
        <h4 class="my-3"> <strong><%= @user.full_name %></strong> </h4>
          <hr style="background-color: black; width: 50px;">
          <% @user.teaching_subjects.each do |s| %>
            <div class="tag"><%= s.name %></div>
          <% end %>
          <div class="extra-info my-4">
            <div class="d-flex justify-content-center">
              <p> <i class="fas fa-language"></i> <%= @user.language %></p>
              <p class="ml-5"> <i class="fas fa-map-marker-alt"></i> <%= @user.location %></p>
            </div>
            <div class="d-flex justify-content-center">
              <p >
                <% if @user.price.present? %>
                  <i class="fas fa-euro-sign"></i> <%= @user.price %>/Hour</p>
               <% end %>
              <p class="ml-5">
                <i class="far fa-star"></i> <%= @user.average_ratings if @user.received_reviews.present?%> (<%= @user.received_reviews.count %> reviews)</p>
            </div>
            </div>
            <hr style="background-color: black; width: 50px;">
            <div class="buttons">
              <% if @user.teaching_subjects.present? %>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-flat my-2" data-toggle="modal" data-target="#staticBackdrop" <%= 'disabled' unless user_signed_in? %>>
                Book a session
              </button>
              <% end %>
               <br>
              <%= link_to 'Message', chats_path(sender_id: current_user, recipient_id: @user), method: :post, class: 'btn btn-ghost' %>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-ghost" data-toggle="modal" data-target="#staticBackdrop2" <%= 'disabled' unless user_signed_in? %>>
              Review
            </button>

            </div>


            <!-- Modal -->
            <div class="modal fade" id="staticBackdrop2" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Review User</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= render "reviews/form" %>
                  </div>
                </div>
              </div>
            </div>

      </div>



    </div>
    <div class="col-md-6 col-sm-12">
      <div class="descrption">
        <h2 class="heading">About me</h2>
        <p><%= @user.bio %></p>
      </div>
    </div>
  </div>
</div>

  <div class="container">
    <div class="row">
        <h2 class="sub-heading"><%= @user.name %>'s reviews</h2>
        <% if @user.received_reviews.present? %>
          <% @user.received_reviews.each do |r| %>
            <div class="col-12">
              <div class="review-card my-4">
                <div class="top d-flex justify-content-between">
                  <div class="left">
                    <% if r.reviewer.photo.attached? %>
                      <%= cl_image_tag r.reviewer.photo.key, crop: :thumb, gravity: :face, width: 80, height: 80, class: "rounded-circle dropdown-toggle" %>
                    <% else %>
                        <img src="https://image.flaticon.com/icons/svg/847/847969.svg" width="80" alt="">
                    <% end %>
                    <strong><%= r.reviewer.full_name %></strong>
                  </div>
                  <div class="right text-right">
                      <% 5.times do |x| %>
                        <i class="far fa-star" style="color: <%= x < r.stars ? 'red' : 'black'  %>;"></i>
                      <% end %>
                      <p style="color: lightgray"><%= time_ago_in_words(r.created_at)%> ago</p>
                  </div>
                </div>
                <div class="bottom mt-2">
                  <%= r.content %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
        <div class="col-12">
          <p>No reviews yet</p>
        </div>
        <% end %>
  </div>
  </div>




<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="staticBackdropLabel">When do you want to meet your Mentor</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="row">
                      <div class="col-12">
                        <div class="modal-body">

                          <%= simple_form_for([@user, @booking]) do |f| %>
                            <div class="row">
                              <div class="col-12">
                                <%= f.input :start_date, as: :string, placeholder: 'Day', input_html: {class: 'kasi flatpickr box'}%>
                                <%= f.input :duration, collection: (1..4), include_blank: false %>

                              </div>
                              <div class="col-12">
                                <%= f.submit 'Request booking', class: 'btn btn-success booking' %>
                              </div>
                            </div>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>