config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :after_signup
  root to: 'pages#home'
  resource :dashboard, only: :show
  get "/results", to: 'users#index', as: "results"
  get "/autocomplete", to: 'users#autocomplete'
  get "/allbookings", to: 'dashboards#allbookings', as: "allbookings"
  get "/allearnings", to: 'dashboards#allearnings', as: "allearnings"
  get "/users/:id", to: 'users#profile', as: "profile"

  resources :chats, only: [:index, :create, :show] do
   resources :messages, only:  :create
  end
  resources :users do
  	resources :bookings, only: :create
    resources :reviews, only: [:create]
  end

  resources :bookings, only: :update do
     resources :payments, only: :new
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="row footer">
  <div class="col-sm-12 col-lg-6 ">
    <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  </div>
  <div class="col-sm-12 col-lg-6 my-3 mx-auto">
    <div class="subscribe">
      <h4 style="color: white;" class="sub-heading">Get tips on how to study</h4>
      <form action="/newsletter" method="post">
        <input type="text" placeholder="foo@bar.com">
        <a class="btn btn-flat" href="#">Subcribe</a>
      </form>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo2.png", :class => "style_img" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item ">
          <%= link_to "Find A Buddy", results_path, class: "btn btn-ghost mr-3" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", chats_path, class: "btn btn-ghost mr-3" %>
        </li>
        <li class="nav-item dropdown" style="cursor: pointer;">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face, width: 50, height: 50, class: "rounded-circle dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
          <% else %>
            <img src="https://image.flaticon.com/icons/svg/847/847969.svg" class="avatar dropdown-toggle", id="navbarDropdown", data-toggle="dropdown", aria-haspopup="true", aria-expanded="false"  >
          <% end %>

          <div class="dropdown-menu dropdown-menu-right sb-dropdown" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item btn btn-flat-login">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        <li class="nav-item btn btn-flat-login">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>


<!-- <nav class="navbar fixed-top navbar-light bg-light">
  <a class="navbar-brand" href="#">Fixed top</a>
</nav>
 -->