config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :after_signup
  root to: 'pages#home'
  resource :dashboard, only: :show
  get "/results", to: 'users#index', as: "results"
  get "/autocomplete", to: 'users#autocomplete'
  get "/allbookings", to: 'dashboards#allbookings', as: "allbookings"
  get "/allearnings", to: 'dashboards#allearnings', as: "allearnings"
  get "/users/:id", to: 'users#profile', as: "profile"

  resources :chats, only: [:index, :create, :show] do
   resources :messages, only:  :create
  end
  resources :users do
  	resources :bookings, only: :create
    resources :reviews, only: [:create]
  end

  resources :bookings, only: :update do
     resources :payments, only: :new
   end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @reviews = Review.where(reviewed_id: current_user.id)
    authorize :dashboard, :show?
  end

  def allbookings
    authorize :dashboard, :allbookings?
  end

  def allearnings
    authorize :dashboard, :allearnings?
  end
end

app/views/dashboards/allbookings.html.erb
<div class="container my-4">
  <div class="mx-auto form-frame" style="width: 900px;">

  <div class="row">
    <h2 class="col-12 sub-heading">Your bookings</h2>
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Student</th>
            <th scope="col">Date</th>
            <th scope="col">Duration (hours)</th>
            <th scope="col">Total</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <% current_user.received_bookings.each do |booking| %>
            <tr>
              <td> <%= link_to booking.student.full_name, profile_path(booking.student)  %></td>
              <td><%= booking.start_date.month %>/<%= booking.start_date.day %>/<%= booking.start_date.year %></td>
              <td><%= booking.duration %> </td>
              <td><%= humanized_money_with_symbol(booking.total) %></td>
              <td><%= booking.status %>
                <%= link_to booking_path(booking, status: :accepted), method: :patch do  %>
                  <i style="color: green" class="fas fa-check-circle"></i>
                <% end %>
                <%= link_to booking_path(booking, status: :rejected), method: :patch do  %>
                  <i style="color: red" class="fas fa-minus-circle"></i>
                <% end %>


              </td>
          <% end %>

          </tr>
        </tbody>
      </table>
    </div>
  </div>


<br>
<br>

  <div class="row">
    <h2 class="col-12 sub-heading">Bookings made</h2>
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Student</th>
            <th scope="col">Date</th>
            <th scope="col">Duration (hours)</th>
            <th scope="col">Total</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <% current_user.sent_bookings.each do |booking| %>
            <tr>
              <td> <%= link_to booking.mentor.full_name, profile_path(booking.mentor)  %></td>
              <td><%= booking.start_date.month %>/<%= booking.start_date.day %>/<%= booking.start_date.year %></td>
              <td><%= booking.duration %> </td>
              <td><%= humanized_money_with_symbol(booking.total) %></td>
              <td><%= booking.status %>


              </td>
          <% end %>

          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/dashboards/allearnings.html.erb
<div class="container my-4">
  <div class="row">
    <h2 class="col-12 sub-heading">Your Reviews</h2>
    <div class="col-12">
      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">Student</th>
            <th scope="col">Date</th>
            <th scope="col">Duration (hours)</th>
            <th scope="col">Total</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <% current_user.received_bookings.each do |booking| %>
            <tr>
              <td> <%= link_to booking.student.full_name, profile_path(booking.student)  %></td>
              <td><%= booking.start_date.month %>/<%= booking.start_date.day %>/<%= booking.start_date.year %></td>
             <td><%= booking.duration %> </td>
              <td><%= humanized_money_with_symbol(booking.total) %></td>
              <td>Status</td>
          <% end %>

          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/dashboards/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-8">
      <div class="box profile-notification text-center">
        <p>Your profile is <%= current_user.completion_percentage %>% completed</p>
        <%= link_to 'Finish now', edit_user_registration_path %>
      </div>
    </div>
    <div class="col">
      <div class="box dashboard-info-box">
        <div class="left">
          <h5><%= current_user.full_name %></h5>
          <p><img src="https://image.flaticon.com/icons/svg/3094/3094812.svg" width="30" alt="">
            444 reviews
            </p>
        </div>
        <div class="right">
          <%= link_to edit_user_registration_path do %>
            <i class="fas fa-ellipsis-v"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row my-3">
    <div class="col-6">
      <div class="box dashboard-section">
        <h5 class="sub-heading">Booking requests</h5>
        <p>You have 2 requests pendings</p>
        <%= link_to 'Answer requests', root_url, class: 'btn btn-flat'  %>
      </div>
    </div>
    <div class="col-6">
      <div class="box dashboard-section">
        <h5 class="sub-heading">Earnings</h5>
        <h5>You earned 220 euros</h5>
        <%= link_to 'View history', root_url, class: 'btn btn-flat'  %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/dashboards/show.html.erb
<% content_for :title, "My Dashboard | #{current_user.full_name}" %>
<div style="height: 100px;"></div>
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="profile-notification text-center">
        <h5><%= current_user.full_name %></h5>
        <p>Your profile is <%= current_user.completion_percentage %>% completed</p>
        <%= link_to 'Edit', edit_user_registration_path %>
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: <%= current_user.completion_percentage %>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row text-center w-75 mx-auto" id="stat">
    <div class="col-sm-12 col-lg">
      <div class="box1">
        <i class="fas fa-money-bill-alt"></i>
        <p class="count"> <%= current_user.earnings / 100%> Euros</p>
        <p>earned</p>
      </div>
    </div>
    <div class="col-sm-12 col-lg">
      <div class="box1">
        <i class="fas fa-chalkboard-teacher"></i>
        <p class="count"><%= current_user.received_bookings.count %></p>
        <p>Booking requests</p>
      </div>
    </div>
    <div class="col-sm-12 col-lg">
      <div class="box1">
        <i class="fas fa-user-graduate"></i>
        <p class="count"><%= current_user.sent_bookings.count %></p>
        <p>Bookings made</p>
      </div>
    </div>
    <div class="col-sm-12 col-lg">
      <div class="box1">
        <i class="fas fa-star"></i>
        <p class="count"><%= @reviews.count %></p>
        <p>Reviews</p>
      </div>
    </div>
  </div>
</div>

<br>
<br>

<div class="container">
  <div class="row center">
    <div class="col">
      <ul class="nav nav-pills justify-content-center" id="pills-tab" role="tablist">
        <!-- <li class="nav-item">
          <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Pending requests</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Your bookings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Your reviews</a>
        </li>
      </ul>
      <div class="tab-content" id="pills-tabContent">


        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab"><div class="container my-4">
  <div class="mx-auto form-frame" style="width: 900px;">

  <div class="row">
    <h2 class="col-12 sub-heading">All bookings</h2>
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Student</th>
            <th scope="col">Date</th>
            <th scope="col">Duration (hours)</th>
            <th scope="col">Total</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <% current_user.received_bookings.each do |booking| %>
            <tr>
              <td> <%= link_to booking.student.full_name, profile_path(booking.student)  %></td>
              <td><%= booking.start_date.month %>/<%= booking.start_date.day %>/<%= booking.start_date.year %></td>
             <td><%= booking.duration %> </td>
              <td><%= humanized_money_with_symbol(booking.total) %></td>
              <td><%= booking.status %>
                <%= link_to booking_path(booking, status: :accepted), method: :patch do  %>
                  <i style="color: green" class="fas fa-check-circle"></i>
                <% end %>
                <%= link_to booking_path(booking, status: :rejected), method: :patch do  %>
                  <i style="color: red" class="fas fa-minus-circle"></i>
                <% end %>


              </td>
          <% end %>

          </tr>
        </tbody>
      </table>
    </div>
  </div>


<br>
<br>

  <div class="row">
    <h2 class="col-12 sub-heading">Bookings made</h2>
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Student</th>
            <th scope="col">Date</th>
            <th scope="col">Duration (hours)</th>
            <th scope="col">Total</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <% current_user.sent_bookings.each do |booking| %>
            <tr>
              <td> <%= link_to booking.mentor.full_name, profile_path(booking.mentor)  %></td>
              <td><%= booking.start_date.month %>/<%= booking.start_date.day %>/<%= booking.start_date.year %></td>
              <td><%= booking.duration %> </td>
              <td><%= humanized_money_with_symbol(booking.total) %></td>
              <td><%= booking.status %>


              </td>
          <% end %>

          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>
</div>

        <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab"><div class="container">
    <div class="row justify-content-center">
        <h2 class="dash1"><%= current_user.name %>'s reviews</h2>
        <% if current_user.received_reviews.present? %>
          <% current_user.received_reviews.each do |r| %>
            <div class="col-12">
              <div class="review-card my-4">
                <div class="top d-flex justify-content-between">
                  <div class="left">
                    <% if r.reviewer.photo.attached? %>
                      <%= cl_image_tag r.reviewer.photo.key, crop: :thumb, gravity: :face, width: 80, height: 80, class: "rounded-circle dropdown-toggle" %>
                    <% else %>
                        <img src="https://image.flaticon.com/icons/svg/847/847969.svg" width="80" alt="">
                    <% end %>
                    <strong><%= r.reviewer.full_name %></strong>
                  </div>
                  <div class="right">
                      <% 5.times do |x| %>
                        <i class="far fa-star" style="color: <%= x < r.stars ? 'red' : 'black'  %>;"></i>
                      <% end %>
                      <p style="color: lightgray"><%= time_ago_in_words(r.created_at)%> ago</p>
                  </div>
                </div>
                <div class="bottom mt-2 text-left">
                  <%= r.content %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
        <div class="col-12">
          <p>No reviews yet</p>
        </div>
        <% end %>
  </div>
  </div></div>
      </div>
    </div>
  </div>
</div>